# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"_\n\x0fRequestVoteArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"5\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\")\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"\x95\x01\n\x11\x41ppendEntriesArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\"3\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"$\n\rPartitionArgs\x12\x13\n\x0b\x62locked_ips\x18\x01 \x03(\t\"!\n\x0ePartitionReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd0\x01\n\x0bRaftService\x12>\n\x0bRequestVote\x12\x15.raft.RequestVoteArgs\x1a\x16.raft.RequestVoteReply\"\x00\x12\x44\n\rAppendEntries\x12\x17.raft.AppendEntriesArgs\x1a\x18.raft.AppendEntriesReply\"\x00\x12;\n\x0cSetPartition\x12\x13.raft.PartitionArgs\x1a\x14.raft.PartitionReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTVOTEARGS']._serialized_start=20
  _globals['_REQUESTVOTEARGS']._serialized_end=115
  _globals['_REQUESTVOTEREPLY']._serialized_start=117
  _globals['_REQUESTVOTEREPLY']._serialized_end=170
  _globals['_LOGENTRY']._serialized_start=172
  _globals['_LOGENTRY']._serialized_end=213
  _globals['_APPENDENTRIESARGS']._serialized_start=216
  _globals['_APPENDENTRIESARGS']._serialized_end=365
  _globals['_APPENDENTRIESREPLY']._serialized_start=367
  _globals['_APPENDENTRIESREPLY']._serialized_end=418
  _globals['_PARTITIONARGS']._serialized_start=420
  _globals['_PARTITIONARGS']._serialized_end=456
  _globals['_PARTITIONREPLY']._serialized_start=458
  _globals['_PARTITIONREPLY']._serialized_end=491
  _globals['_RAFTSERVICE']._serialized_start=494
  _globals['_RAFTSERVICE']._serialized_end=702
# @@protoc_insertion_point(module_scope)
